name: Python application

on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python collector.py
        python frag.py
        
    - name: Commit and push changes
      run: |
        git config --local user.name 'github-actions'
        git config --local user.email 'github-actions@github.com'
        git add v2ray_configs.txt fragment.txt
        git commit -m 'Update v2ray_configs.txt and fragment.txt'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
